name: Build and Release ZIP

on:
  push:
    branches:
      - main  # ou une autre branche cible

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Préparer les fichiers
        run: |
          mkdir output
          echo "Fichier exemple" > output/exemple.txt

      - name: Créer une archive ZIP
        run: |
          zip -r petyma_be.mcpack output

      - name: Upload zip
        uses: actions/upload-artifact@v4
        with:
          name: petyma_be
          path: petyma_be.mcpack
          retention-days: 7
